classes:
  - common
  - cluster.minikube
  - component.nginx-helm
  - component.nginx-common

parameters:
# These parameters are redundand because automatically set by `common`
## target_name: minikube-nginx-helm
## namespace: ${target_name}