parameters:
  nginx:
    version: 4.4.0
    replicas: 2
    name: ${target_name}
    namespace: ${target_name}
  kapitan:
    dependencies:
      - type: helm
        output_path: charts/nginx-ingress
        source: https://kubernetes.github.io/ingress-nginx
        chart_name: ingress-nginx
    compile:
      - output_path: .
        input_type: helm
        input_paths:
          - charts/nginx-ingress
        helm_values:
          controller:
            name: ${nginx:name}
        helm_params:
          name: ${nginx:name}
          namespace: ${nginx:namespace}