apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch-discovery
  name: elasticsearch-discovery
  namespace: minikube-es-2
spec:
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: transport
  selector:
    name: cluster-master
    role: master
  type: ClusterIP
